"""auto-vote

Revision ID: f25ac02ebcc7
Revises: 168b77e89915
Create Date: 2023-08-08 20:23:31.305815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25ac02ebcc7'
down_revision: Union[str, None] = '168b77e89915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
                    sa.Column('post_id', sa.Integer, sa.ForeignKey("posts.id", ondelete="CASCADE"), primary_key=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
